In [ ]:
import numpy as np #this imports numerical python package which is used for arrays
import pandas as pd #this imports the pandas package which is used for dataframes and to handle the data

import matplotlib.pyplot as plt #this is used for plotting plots
from sklearn.model_selection import train_test_split #it is used for spilting the input data into training and testing datas's
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score #it is used for finding the error in the model 
from sklearn.linear_model import LinearRegression #it is used to import the linear regression model
from sklearn.linear_model import LogisticRegression #it is used to import the logistic regression model
from sklearn.tree import DecisionTreeRegressor #it is used to import the decision tree regression model
from sklearn.svm import SVR #it is used to import the support vector machine model
import seaborn as sns #it is used to draw 3D graphs
%matplotlib inline 

import warnings
warnings.filterwarnings("ignore") #it is used to ignore the warnings if any are produced during runtime

In [ ]:
df = pd.read_csv('/content/Sample - Superstore.csv',encoding='latin-1') #it is used to open the csv file with latin-1 encoding
df.head() #it is used to print the first five rows of the dataset along with the column header

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156  08-11-2016  11-11-2016    Second Class    CG-12520   
1       2  CA-2016-152156  08-11-2016  11-11-2016    Second Class    CG-12520   
2       3  CA-2016-138688  12-06-2016  16-06-2016    Second Class    DV-13045   
3       4  US-2015-108966  11-10-2015  18-10-2015  Standard Class    SO-20335   
4       5  US-2015-108966  11-10-2015  18-10-2015  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [ ]:
df.info() #it is used to know about the features of the dataset and their types
#here non-null count indicates the number of cells in the dataset which have a value
#a null cell contains no data and is empty
#the Dtype of the column indicates the data type of the elements in that column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9994 non-null   int64  
 1   Order ID       9994 non-null   object 
 2   Order Date     9994 non-null   object 
 3   Ship Date      9994 non-null   object 
 4   Ship Mode      9994 non-null   object 
 5   Customer ID    9994 non-null   object 
 6   Customer Name  9994 non-null   object 
 7   Segment        9994 non-null   object 
 8   Country        9994 non-null   object 
 9   City           9994 non-null   object 
 10  State          9994 non-null   object 
 11  Postal Code    9994 non-null   int64  
 12  Region         9994 non-null   object 
 13  Product ID     9994 non-null   object 
 14  Category       9994 non-null   object 
 15  Sub-Category   9994 non-null   object 
 16  Product Name   9994 non-null   object 
 17  Sales          9994 non-null   float64
 18  Quantity

In [ ]:
df.columns #this shows the names of all the columns in the dataset

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df.shape #it is a tuple of (number of rows, number of columns)

(9994, 21)

the features I would take into consideration are sales, quantity, discount

In [ ]:
x = pd.DataFrame({'Sales':df['Sales'],'Quantity':df['Quantity'],'Discount':df['Discount']}) 
#here in x we are creating another data frame with only the features we are taking into consideration
y = np.array(df['Profit'])
#here in y we are making an array of the labels in the dataset

In [ ]:
x.describe() 

Sales     Quantity     Discount
count   9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203
std      623.245101     2.225110     0.206452
min        0.444000     1.000000     0.000000
25%       17.280000     2.000000     0.000000
50%       54.490000     3.000000     0.200000
75%      209.940000     5.000000     0.200000
max    22638.480000    14.000000     0.800000

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1, random_state=42) 
#this is used to split the input dataset into training and testing
#the size of the test data set is 10% of the total input data
#random state is used to retain the value

In [ ]:
linear_r = LinearRegression() 
linear_r.fit(x_train,y_train) #it is used to fit a model to the training dataset

LinearRegression()

In [ ]:
y_pred = linear_r.predict(x_test)
print("R2 of Linear Regression:",r2_score(y_test,y_pred)) 
print("mse of Linear Regression:",mean_squared_error(y_test,y_pred))
print("mae of Linear Regression:",mean_absolute_error(y_test,y_pred))

R2 of Linear Regression: -1.2231713085149472
mse of Linear Regression: 117490.73405500963
mae of Linear Regression: 73.87877392351201


In [ ]:
out_linear_r = linear_r.predict(np.array([209,5,0]).reshape(1,-1)) #it is used to predict the output label for the given input features
out_linear_r

array([51.58140373])

In [ ]:
svr = SVR()
svr.fit(x_train,y_train)

SVR()

In [ ]:
y_pred = svr.predict(x_test)
print('R2 of support vector machine:',r2_score(y_test,y_pred))
print("mse of support vector machine:",mean_squared_error(y_test,y_pred))
print("mae of support vector machine:",mean_absolute_error(y_test,y_pred))

R2 of support vector machine: 0.007026403127897041
mse of support vector machine: 52476.926248062104
mae of support vector machine: 55.970219148736625


In [ ]:
out_svr_r = svr.predict(np.array([209,5,0]).reshape(1,-1))
out_svr_r

array([33.08799672])

In [ ]:
dtree = DecisionTreeRegressor()
dtree.fit(x_train,y_train)

DecisionTreeRegressor()

In [ ]:
y_pred = dtree.predict(x_test)
print("R2 of Decision Tree:",r2_score(y_test,y_pred))
print("mse of decision tree:",mean_squared_error(y_test,y_pred))
print("mae of decision tree:",mean_absolute_error(y_test,y_pred))

R2 of Decision Tree: -1.6796326478912489
mse of decision tree: 141613.92133511123
mae of decision tree: 41.388059789677165


In [ ]:
out_dtree_r = dtree.predict(np.array([209,5,0]).reshape(1,-1))
out_dtree_r

array([52.14])